name: Deploy Develop Branch to Personal Main

on:
  push:
    branches: ["develop"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install mustache (to update the date)
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          sudo gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to personal repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: LazyMG
          destination-repository-name: ivh-home
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
