name: PAT Authentication Test

# 수동으로 직접 실행할 수 있도록 설
on:
  workflow_dispatch:

jobs:
  test-pat-validity:
    runs-on: ubuntu-latest
    steps:
      - name: Test API access to the personal repository
        run: |
          echo "::group::Testing API Request"
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.AUTO_ACTIONS }}" \
            https://api.github.com/repos/LazyMG/ivh-home)
          echo "::endgroup::"
          echo "HTTP Status Code: $RESPONSE_CODE"
          if [ "$RESPONSE_CODE" -eq 200 ]; then
            echo "✅ SUCCESS: The token has a valid 'repo' scope and can access the repository."
          elif [ "$RESPONSE_CODE" -eq 404 ]; then
            echo "❌ FAILURE: The token is valid but the repository 'LazyMG/ivh-home' was not found. Check for typos."
            exit 1
          elif [ "$RESPONSE_CODE" -eq 403 ]; then
            echo "❌ FAILURE: 403 Forbidden. The token is being actively blocked. This confirms a permission issue remains."
            exit 1
          elif [ "$RESPONSE_CODE" -eq 401 ]; then
            echo "❌ FAILURE: 401 Unauthorized. The token string in the AUTO_ACTIONS secret is likely incorrect or has been revoked."
            exit 1
          else
            echo "❌ UNEXPECTED ERROR: Received HTTP status code $RESPONSE_CODE"
            exit 1
          fi```
